### ISSUE TITLE
Fails to compile with clang 8.0.0

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#458]
**Describe the bug**
```
/Users/kbeckwi1/Documents/Projects/EMPIRE/EMPIRE/TPL/vt/src/vt/vrt/collection/balance/lb_invoke/invoke.cc:118:25: error: 'startLBHandler' following the 'template' keyword does not refer to a template
  proxy.get()->template startLBHandler(msg.get(), base_proxy);
                        ^
/Users/kbeckwi1/Documents/Projects/EMPIRE/EMPIRE/TPL/vt/src/vt/vrt/collection/balance/lb_invoke/invoke.cc:153:34: note: in instantiation of function template specialization
      'vt::vrt::collection::balance::LBManager::makeLB<vt::vrt::collection::lb::GossipLB>' requested here
    case LBType::GossipLB:       makeLB<lb::GossipLB>(msg);       break;
                                 ^
/Users/kbeckwi1/Documents/Projects/EMPIRE/EMPIRE/TPL/vt/src/vt/vrt/collection/balance/baselb/baselb.h:89:8: note: declared as a non-template here
  void startLBHandler(balance::StartLBMsg* msg, objgroup::proxy::Proxy<BaseLB> proxy);
```

**Additional context**
Cross-reference issue in EMPIRE: https://cee-gitlab.sandia.gov/EM-Plasma/EMPIRE/issues/1019

**Comment by pnstickne** [comment]
Fixed in origin/develop with merge.
