### ISSUE TITLE
`vt` fails to build with the latest `Kokkos` + CUDA 11.8

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#2344]
**Describe the bug**
`vt` doesn't seem to work with `Kokkos` when CUDA is enabled:
```
kokkos/cmake-build-cuda11_8-debug/install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp(46): error: identifier "vt::phase::PhaseManager::nextPhaseReduce" is undefined in device code
kokkos/cmake-build-cuda11_8-debug/install/include/Cuda/Kokkos_Cuda_KernelLaunch.hpp(46): error: identifier "vt::phase::PhaseManager::nextPhaseDone" is undefined in device code
```

**Additional context**
We currently only have one build with Kokkos enabled:
```
ci/azure/azure-gcc-12-ubuntu-mpich.yml:58:  VT_KOKKOS_ENABLED: 1
```

Azure nvcc builds have Kokkos disabled + we only build with Serial backend anyways (so we can run the tests on nodes without GPU). We could have a separate Azure job that would cover compilation with Kokkos and CUDA backend enabled (with some explicitly provided architecture).

---

@nmm0 can you provide additional details?

**Comment by nmm0** [comment]
I am using nvcc version `11.8`, this only appears in Debug builds

**Comment by JacobDomagala** [comment]
I wasn't able to reproduce the issue. Tried on nvcc 12.3 and 11.2.2 with following build script
```bash
#!/usr/bin/env bash

set -ex

source_dir="/vt"
build_dir="/build"

mkdir -p "${build_dir}"
pushd "${build_dir}"

export VT=${source_dir}
export VT_BUILD=${build_dir}/vt
mkdir -p "$VT_BUILD"
cd "$VT_BUILD"
# rm -Rf ./*

ccache --clear

export Kokkos_enabled=1

# === Step 2: Check if Kokkos_enabled is Set ===
if [ -n "$Kokkos_enabled" ]; then
    export HOST_COMPILER=g++-9
    export CUDA_ROOT="/usr/local/cuda/"

    cd /kokkos/build
    cmake -G "${CMAKE_GENERATOR:-Ninja}" \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
      -DKokkos_ENABLE_CUDA=ON \
      -DKokkos_ARCH_AMPERE80=ON \
      -DKokkos_ENABLE_CUDA_LAMBDA=ON \
      -DKokkos_ENABLE_CUDA_RELOCATABLE_DEVICE_CODE=ON \
      -DCMAKE_INSTALL_PREFIX="/kokkos/build/install" \
      --fresh \
      ..
    cmake --build . --target install
    echo "Kokkos is enabled."

    export CXX="/kokkos/bin/nvcc_wrapper"
    # export CC="/home/jdomagala/Work/nvcc_wrapper"
    cd "$VT_BUILD"
fi

cmake -G "${CMAKE_GENERATOR:-Ninja}" \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
      -Dvt_test_trace_runtime_enabled="${VT_TRACE_RUNTIME_ENABLED:-0}" \
      -Dvt_lb_enabled="${VT_LB_ENABLED:-1}" \
      -Dvt_trace_enabled="${VT_TRACE_ENABLED:-0}" \
      -Dvt_trace_only="${VT_BUILD_TRACE_ONLY:-0}" \
      -Dvt_doxygen_enabled="${VT_DOXYGEN_ENABLED:-0}" \
      -Dvt_mimalloc_enabled="${VT_MIMALLOC_ENABLED:-0}" \
      -Dvt_asan_enabled="${VT_ASAN_ENABLED:-0}" \
      -Dvt_ubsan_enabled="${VT_UBSAN_ENABLED:-0}" \
      -Dvt_werror_enabled="${VT_WERROR_ENABLED:-0}" \
      -Dvt_pool_enabled="${VT_POOL_ENABLED:-1}" \
      -Dvt_build_extended_tests="${VT_EXTENDED_TESTS_ENABLED:-1}" \
      -Dvt_zoltan_enabled="${VT_ZOLTAN_ENABLED:-0}" \
      -Dvt_production_build_enabled="${VT_PRODUCTION_BUILD_ENABLED:-0}" \
      -Dvt_unity_build_enabled="${VT_UNITY_BUILD_ENABLED:-0}" \
      -Dvt_diagnostics_enabled="${VT_DIAGNOSTICS_ENABLED:-1}" \
      -Dvt_diagnostics_runtime_enabled="${VT_DIAGNOSTICS_RUNTIME_ENABLED:-0}" \
      -Dvt_fcontext_enabled="${VT_FCONTEXT_ENABLED:-0}" \
      -Dvt_fcontext_build_tests_examples="${VT_FCONTEXT_BUILD_TESTS_EXAMPLES:-0}" \
      -Dvt_rdma_tests_enabled="${VT_RDMA_TESTS_ENABLED:-1}" \
      -Dvt_code_coverage="${VT_CODE_COVERAGE:-0}" \
      -DMI_INTERPOSE:BOOL=ON \
      -DMI_OVERRIDE:BOOL=ON \
      -Dvt_mpi_guards="${VT_MPI_GUARD_ENABLED:-0}" \
      -DMPI_EXTRA_FLAGS="${MPI_EXTRA_FLAGS:-}" \
      -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE:-Debug}" \
      -DMPI_C_COMPILER="${MPICC:-mpicc}" \
      -DMPI_CXX_COMPILER="${MPICXX:-mpicxx}" \
      -DCMAKE_CXX_COMPILER="${CXX:-g++-9}" \
      -DCMAKE_C_COMPILER="${CC:-gcc-9}" \
      -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS:-}" \
      -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH:-}" \
      -DCMAKE_INSTALL_PREFIX="$VT_BUILD/install" \
      -Dmagistrate_ROOT="/build/magistrate/install" \
      -Dvt_ci_build="${VT_CI_BUILD:-0}" \
      -Dvt_debug_verbose=1 \
      -Dvt_tests_num_nodes=32 \
      -Dvt_external_fmt="${VT_EXTERNAL_FMT:-0}" \
      -Dvt_no_color_enabled="${VT_NO_COLOR_ENABLED:-0}" \
      -DCMAKE_CXX_STANDARD="${CMAKE_CXX_STANDARD:-17}" \
      -DBUILD_SHARED_LIBS="${BUILD_SHARED_LIBS:-0}" \
      --fresh \
      "$VT"


cmake --build . -j 16 --target install

```
