### ISSUE TITLE
Deploy Google Test 1.10 with VT and ensure warnings "go away"

### ISSUE THREAD

**Issue by pnstickne** [DARMA-tasking/vt#595]
GoogleTest deprecated some old API. Clean up the test to use the new method.

```
/Users/pnstick/code/vt/tests/unit/termination/test_termination_action_nested_collect.cc:72:1: warning: 'InstantiateTestCase_P_IsDeprecated' is deprecated: INSTANTIATE_TEST_CASE_P is deprecated, please use
      INSTANTIATE_TEST_SUITE_P [-Wdeprecated-declarations]
INSTANTIATE_TEST_CASE_P /* NOLINT */(
^
/Users/pnstick/opt-clang/googletest/include/gtest/gtest-param-test.h:507:38: note: expanded from macro 'INSTANTIATE_TEST_CASE_P'
  static_assert(::testing::internal::InstantiateTestCase_P_IsDeprecated(), \
                                     ^
/Users/pnstick/opt-clang/googletest/include/gtest/internal/gtest-internal.h:1220:1: note: 'InstantiateTestCase_P_IsDeprecated' has been explicitly marked deprecated here
GTEST_INTERNAL_DEPRECATED(
^
/Users/pnstick/opt-clang/googletest/include/gtest/internal/gtest-port.h:2203:59: note: expanded from macro 'GTEST_INTERNAL_DEPRECATED'
#define GTEST_INTERNAL_DEPRECATED(message) __attribute__((deprecated(message)))
                                                          ^
/Users/pnstick/code/vt/tests/unit/termination/test_termination_action_nested_collect.cc:72:1: error: expected expression
INSTANTIATE_TEST_CASE_P /* NOLINT */(
^
```

The new API is (most likely) already in 1.8.1; so it's probably a clean forward-migration.

Also might be useful to pin a higher googletest required version (as well as to update the CMake for a few small let-me-use-my-debug-libs).

**Comment by lifflander** [comment]
We do need to be careful with EMPIRE. It relies on an older version of gtest and we may not be able to upgrade that. I'm not sure about the coexistance of multiple versions of gtest, in theory its possible with CMake, private deps.

**Comment by pnstickne** [comment]
Working on a 'shim' approach - `1.10` added va_args to instantiating typed tests.. which generates new warnings :|

**Comment by pnstickne** [comment]
Also using (requiring) an independent gtest version would be a potentially useful divide. Uhg, what version does EMPIRE use?

**Comment by pnstickne** [comment]
@lifflander Going to leave this story as 'compatible between'.. to facilitate forward migrations. Next will be to switch to the (newer) CMake test detection that does not rely on regular expression scanning. That will require some test updates for .. useful ness.

**Comment by pnstickne** [comment]
A task, not a bug..
..ensure clean compilations without warnings and forward-compatibility while supporting 1.18.1 (final) through 1.10.1 _and_ the specific pre-1.18.1 version by Empire.

**Comment by lifflander** [comment]
@pnstickne Can you try to finish this by packaging google test in vt/lib and isolating the includes to the tests?
