### ISSUE TITLE
fix missing `<cstdint>` include

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/vt#2225]
**Describe the bug**
`vt` fails to build with `clang 16.0.6` on Fedora 38:
```
/vt/src/vt/configs/error/stack_out.h:54:44: error: use of undeclared identifier 'uint64_t'
using StackTupleType  = std::tuple<int32_t,uint64_t,std::string,std::size_t>;
                                           ^
```

This is because of [changes in Standard Library headers in GCC 13](https://gcc.gnu.org/gcc-13/porting_to.html) (see `Header dependency changes`).
