### PR TITLE
2062 Fix duplicate symbols on some Mac builds

### LINKED ISSUE #2062: Fix duplicate symbols on some Mac builds
**Describe the bug**
Some vt executables and vt-enabled apps get link errors on Mac:
```
duplicate symbol 'typeinfo name for vt::pool::MemoryPoolEqual<64ll, true>' in:
    src/libvt-debug.a(memory_pool_equal.cc.o)
    src/libvt-debug.a(runnable.cc.o)
duplicate symbol 'typeinfo for vt::pool::MemoryPoolEqual<64ll, true>' in:
    src/libvt-debug.a(memory_pool_equal.cc.o)
    src/libvt-debug.a(runnable.cc.o)
duplicate symbol 'typeinfo name for vt::pool::MemoryPoolEqual<1024ll, true>' in:
    src/libvt-debug.a(memory_pool_equal.cc.o)
    src/libvt-debug.a(runnable.cc.o)
duplicate symbol 'typeinfo for vt::pool::MemoryPoolEqual<1024ll, true>' in:
    src/libvt-debug.a(memory_pool_equal.cc.o)
    src/libvt-debug.a(runnable.cc.o)
```
This appears to be related to the `#include "src/vt/pool/static_sized/memory_pool_equal.cc"` line at the end of `src/vt/runnable/runnable.cc`. That `#include` is required, but it seems like the build system is also building `memory_pool_equal.cc` separately due to the `.cc` extension, which can result in linking errors. Rename `memory_pool_equal.cc` so that it doesn't get built separately.

### PR DESCRIPTION
**Pull request by nlslatt**
Fixes #2062

### CODE REVIEW

**Review by PhilMiller — APPROVED** [review]
I saw the discussion about this, and agree with the solution.
